# Generated by Django 5.1.2 on 2025-01-25 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor/images/')),
                ('fee', models.IntegerField()),
                ('meet_link', models.CharField(max_length=100)),
                ('available_time', models.ManyToManyField(to='doctor.availabletime')),
                ('designation', models.ManyToManyField(to='doctor.designation')),
                ('specialization', models.ManyToManyField(to='doctor.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
